server:
  port: ${SERVER_PORT}
  tomcat:
    max-swallow-size: -1

swagger:
  uri: ${SWAGGER_URI}

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

spring:
  jackson:
    time-zone: ${JSON_TIME_ZONE}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
    hikari:
      maximum-pool-size: 40 # 최대 커넥션 수
      minimum-idle: 10  # 최소 유휴 커넥션 수
      idle-timeout: 300000  # 5분
      max-lifetime: 540000  # 9분
      keepalive-time: 240000  # 4분 (idle 커넥션 주기적 ping)
      connection-timeout: 10000 # 10초
      leak-detection-threshold: 20000 # 20초
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL}
        jdbc:
          time_zone: ${JPA_TIME_ZONE}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: "${REDIS_PASSWORD}"
      fail-fast: ${REDIS_FAIL_FAST}

    mongodb:
      uri: ${MONGODB_URI}

  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_ID}
    password: ${RABBIT_MQ_PASSWORD}
    virtual-host: /

rabbitmq:
  chat-queue:
    name: "chat.queue"
  chat-exchange:
    name: "chat.exchange"
  chat-routing:
    key: "chat.room.*"

snowflake:
  node-id: ${SNOWFLAKE_NODE_ID}
